# Generated by Django 4.0.4 on 2022-08-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.SmallIntegerField(choices=[(1, 'On wait'), (2, 'Payed'), (-1, 'Cancelled')])),
                ('amount', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=13)),
                ('amount', models.IntegerField(default=0)),
                ('account', models.IntegerField(default=0)),
                ('create_time', models.BigIntegerField(default=0)),
                ('perform_time', models.BigIntegerField(default=0)),
                ('cancel_time', models.BigIntegerField(default=0)),
                ('transaction', models.CharField(max_length=50)),
                ('state', models.SmallIntegerField(choices=[(1, 'Created'), (2, 'Payed'), (-1, 'Cancelled'), (-2, 'Cancelled after payed')])),
                ('reason', models.SmallIntegerField(choices=[(1, 'User not found error'), (2, 'Debit operation error'), (3, 'Execution error'), (4, 'Timeout cancel error'), (5, 'Refund'), (6, 'Undefined error')], default=0)),
                ('receivers', models.CharField(max_length=500)),
            ],
        ),
    ]
