# Generated by Django 4.0.4 on 2022-08-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.IntegerField(choices=[(1, 'Silver'), (2, 'Gold'), (3, 'Platinum')], default=0),
        ),
    ]
