# Generated by Django 4.0.4 on 2022-08-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_account_payment_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='dfg', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.SmallIntegerField(choices=[(1, 'On wait'), (2, 'Payed'), (-1, 'Cancelled')], default=1),
        ),
    ]
