# Generated by Django 4.0.6 on 2022-08-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_payment_amount_payment_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=15)),
                ('plan', models.IntegerField(choices=[(1, 'Standart'), (2, 'Premium'), (3, 'VIP')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='usd_course',
            field=models.FloatField(default=11015.0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.IntegerField(choices=[(1, 'Standart'), (2, 'Premium'), (3, 'VIP')], default=0),
        ),
    ]
