# Generated by Django 4.0.6 on 2022-08-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_justrequest_payment_usd_course_alter_payment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='usd_course',
            field=models.IntegerField(default=11015.0),
        ),
    ]
