# Generated by Django 4.0.6 on 2022-08-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_payment_usd_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='usd_course',
            field=models.FloatField(default=11015.0),
        ),
    ]
